### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/MI-000-SS00-000-js-intro-Vh2K33#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://KatieMFritz.github.io/MI-000-SS00-000-js-intro-Vh2K33/) and meets the following criteria:

- [x] Include at least 3 `button` elements in your page
- [x] When any of the buttons are hovered over (`mouseenter` event) or clicked on (`click` event), a unique sound effect will play from an `audio` element (try the `.play()` method) -- you may use [these drum kit sounds](/static/audio/drum-sounds.zip), create ones from [this sound effects generator](http://sfbgames.com/chiptone/), or use any other sounds that won't hurt/irritate the people who listen to them
- [x] Each button is well-labeled, corresponding to the sound it will play
- [x] All `audio` elements are invisible (no `controls` attribute), so that they can only be played with the buttons

I just used `play` instead of including `audio` elements on the page.

**Comment by chrisvfritz** [comment]
Magnifico! 🌟 🎈 :shipit: 🏎
